"""initial commit

Revision ID: 5e5244f799a0
Revises: 
Create Date: 2023-04-01 18:29:01.448509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5244f799a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('senha', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('fotoPerfil', sa.String(), nullable=True),
    sa.Column('stacks', sa.String(), nullable=False),
    sa.Column('areas', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('fotoPost', sa.String(), nullable=True),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('dataCriacao', sa.DateTime(), nullable=False),
    sa.Column('idUsuario', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('corpo', sa.Text(), nullable=False),
    sa.Column('idPost', sa.Integer(), nullable=True),
    sa.Column('idUsuario', sa.Integer(), nullable=True),
    sa.Column('dataCriacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['idPost'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['idUsuario'], ['usuario.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('post')
    op.drop_table('usuario')
    # ### end Alembic commands ###
